name: Build FastHopper JAR

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Code herunterladen
        uses: actions/checkout@v4

      - name: Java 21 einrichten
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Struktur anzeigen
        run: find . -name "pom.xml"

      - name: JAR bauen
        run: cd FastHopper && mvn clean package

      - name: Fertige JAR hochladen
        uses: actions/upload-artifact@v4
        with:
          name: FastHopper
          path: FastHopper/target/FastHopper-1.0.0.jar
